name: BonDriverProxyEx_Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - x64
          - Win32
        configuration:
          - Release
          - Release_DLL
          - Debug
          - Debug_DLL

    steps:
      - name: Checkout BonDriverProxyEx
        uses: actions/checkout@v4
        with:
          path: ./BonDriverProxyEx

      - name: Checkout libaribb25
        uses: actions/checkout@v4
        with:
          repository: tkmsst/libaribb25
          path: ./libaribb25

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: File Copy
        run: |
          copy -R ./libaribb25/aribb25 ./BonDriverProxyEx/BonDriverProxyEx -Force

      - name: MSBuild
        run: |
          cd BonDriverProxyEx
          MSBuild BonDriverProxyEx.sln /t:rebuild /p:Configuration="${{ matrix.configuration }}" /p:Platform="${{ matrix.platform }}" /p:PlatformToolset=v143

      - name: File Copy
        run: |
          cd BonDriverProxyEx
          mkdir Build
          copy -R ./${{ matrix.platform }}/${{ matrix.configuration }} ./Build
          copy BonDriver_Proxy_Sample.ini ./Build
          copy BonDriverProxyEx_Sample.ini ./Build
          copy LICENSE.txt ./Build
          copy MEMO.txt ./Build
          copy README.md ./Build

      - name: Upload asset
        uses: actions/upload-artifact@v4
        with:
          name: BonDriverProxyEx_${{ matrix.platform }}_${{ matrix.configuration }}
          path: BonDriverProxyEx/Build
